backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "case-studies"
    label: "Case Studies"
    label_singular: "Case Study"
    folder: "src/pages/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "case-studies"}
      - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Partner Name", name: "partnerName", widget: "string"}
      - {label: "Texture", name: "texture", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Secondary Layout", name: "secondaryLayout", widget: "boolean"}
      - {label: "Modified Texture", name: "modifiedTexture", widget: "boolean", default: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Home Image", name: "homeimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: Meta Title, name: metaTitle, widget: string}
      - {label: Meta Description, name: metaDescription, widget: string}

  - name: "blog-posts"
    label: "Blog"
    label_singular: "Blog Post"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Headline", name: "headline", widget: "string"}
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "employees"
        searchFields: ["name", "position"]
        valueField: "name"
        displayField: "name"
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean"}
      - label: "Featured Color"
        name: "featuredColor"
        widget: "select"
        options:
         - { label: "Fresh", value: "-fresh" }
         - { label: "After Hours", value: "-after-hours" }
         - { label: "Violet Blue", value: "-violet-blue" }
         - { label: "Throwback Pink", value: "-throwback-pink" }
         - { label: "Siracha", value: "-siracha" }
         - { label: "Tea", value: "-tea" }
         - { label: "Eraser", value: "-eraser" }
         - { label: "Sticky Blue", value: "-sticky-blue" }
         - { label: "Center Lane", value: "-center-lane" }
        default: { label: "Fresh", value: "-fresh" }
      - label: "Featured Image"
        name: "featuredimage"
        widget: "object"
        fields:
         - {label: "Image", name: "image", widget: "image"}
         - {label: "Description", name: "description", widget: "string"}
      - label: "Tile Image"
        name: "tileimage"
        widget: "object"
        fields:
         - {label: "Image", name: "image", widget: "image"}
         - {label: "Description", name: "description", widget: "string"}
      - label: "Post Image"
        name: "postimage"
        widget: "object"
        fields:
         - {label: "Image", name: "image", widget: "image"}
         - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Agency", "Agile", "Behind the Scenes", "Brands", "Case Study", "Catamaran", "Design", "Software Development and Engineering", "Strategy", "User Experience"]
        default: "Agency"
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
         - {label: Meta Title, name: metaTitle, widget: string}
         - {label: Meta Description, name: metaDescription, widget: string}

  - name: "employees"
    label: "Employees"
    label_singular: "Employee"
    folder: "src/data/employees"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Create Page", name: "createPage", widget: "hidden", default: false}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Job Title", name: "position", widget: "string"}
      - {label: "Easter Egg", name: "easterEgg", widget: "string"}
      - label: "Photo"
        name: "photo"
        widget: "object"
        fields:
         - {label: "Image", name: "image", widget: "image"}
         - {label: "Description", name: "description", widget: "string"}
      - label: "Social Links"
        label_singular: "Link"
        name: "social-links"
        widget: "list"
        fields:
        - label: "Platform"
          name: "platform"
          widget: "select"
          options: ["Dribbble", "Facebook", "GitHub", "Instragram", "LinkedIn", "Twitter"]
        - {label: "URL", name: "url", widget: "string"}

  - name: "careers"
    label: "Careers"
    label_singular: "Career"
    folder: "src/pages/careers"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "careers"}
      - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Link", name: "position", widget: "string"}
      - {label: Meta Title, name: metaTitle, widget: string}
      - {label: Meta Description, name: metaDescription, widget: string}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
          - {label: Title, name: title, widget: string}
          - {label: Secondary, name: secondaryTitle, widget: string}
          - {label: Subtitle, name: subTitle, widget: string}
          - {label: Meta Title, name: metaTitle, widget: string}
          - {label: Meta Description, name: metaDescription, widget: string}

      - file: "src/pages/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
          - {label: Title, name: title, widget: string}
          - {label: Secondary, name: secondaryTitle, widget: string}
          - {label: Subtitle, name: subTitle, widget: string}
          - {label: Street Address Line One, name: streetAddressLineOne, widget: string}
          - {label: Street Address Line Two, name: streetAddressLineTwo, widget: string}
          - {label: Map Link, name: mapLink, widget: string}
          - {label: Phone Number, name: phoneNumber, widget: string}
          - {label: Directions, name: directions, widget: string}
          - {label: Meta Title, name: metaTitle, widget: string}
          - {label: Meta Description, name: metaDescription, widget: string}
      - file: "src/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
          - {label: Title, name: title, widget: string}
          - {label: Secondary, name: secondaryTitle, widget: string}
          - {label: Subtitle, name: subTitle, widget: string}
          - {label: Meta Title, name: metaTitle, widget: string}
          - {label: Meta Description, name: metaDescription, widget: string}
